# Generated by Django 5.2.15 on 2026-09-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='update_at',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
